#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/helpers.star", "image_reference", "image_pull_policy")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "eduk8s-operator"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: eduk8s
        #@ image = image_reference("system-operator")
        image: #@ image
        imagePullPolicy: #@ image_pull_policy(image)
