#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata": {"name": "eduk8s"}})
---
metadata:
  #@overlay/match missing_ok=True
  name: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "eduk8s-operator"}})
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata": {"name": "eduk8s"}})
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"ClusterRoleBinding", "metadata": {"name": "eduk8s-cluster-admin"}})
---
subjects:
#@overlay/match by="name"
- name: eduk8s
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace
