---
#! overlay-serviceaccount.yaml

#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata":{"name":"eduk8s"}})
---
metadata:
  #@ overlay/match missing_ok=True
  namespace: #@ data.values.namespace
