---
#! overlay-rolebinding.yaml

#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"ClusterRoleBinding", "metadata":{"name":"eduk8s-cluster-admin"}})
---
subjects:
#@overlay/match by="name"
- name: eduk8s
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace
