#@ load("@ytt:data", "data")

apiVersion: v1
kind: ConfigMap
metadata:
  name: eduk8s-images
  namespace: #@ data.values.namespace
data:
  PORTAL_IMAGE: #@ data.values.images.training-portal
  BASE_ENVIRONMENT_IMAGE: #@ data.values.images.base-environment
  JDK8_ENVIRONMENT_IMAGE: #@ data.values.images.jdk8-environment
  JDK11_ENVIRONMENT_IMAGE: #@ data.values.images.jdk11-environment
  CONDA_ENVIRONMENT_IMAGE: #@ data.values.images.conda-environment
