#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduk8s-operator
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: eduk8s-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: eduk8s-operator
    spec:
      serviceAccountName: eduk8s
      containers:
      - name: eduk8s
        image: #@ data.values.imageVersions.platform.operator
        #@ tag = data.values.imageVersions.platform.operator.split(":")
        #@ always = len(tag) <= 1 or tag[-1] in ["latest", "main", "master", "develop"]
        imagePullPolicy: #@ always and "Always" or "IfNotPresent"
        envFrom:
        - configMapRef:
            name: eduk8s-images
            optional: true
