---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.15.0
overrides:
- image: quay.io/eduk8s/eduk8s-operator:develop
  newImage: quay.io/eduk8s/eduk8s-operator:210508.025026.38e63af
