#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("/helpers.star", "docker_config_json")

#@ hostname = data.values.imageRegistry.hostname
#@ username = data.values.imageRegistry.username
#@ password = data.values.imageRegistry.password or ""

#@ if hostname and username:
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-pull".format(hostname)
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ base64.encode(docker_config_json(hostname, username, password))
#@ end
