#@ load("@ytt:data", "data")
#@ load("/helpers.star", "image_pull_secrets")

apiVersion: training.eduk8s.io/v1alpha1
kind: SystemProfile
metadata:
  name: default-system-profile
spec:
  ingress:
    domain: #@ data.values.ingressDomain
    #@ certificate = data.values.ingressSecret.certificate
    #@ privateKey = data.values.ingressSecret.privateKey
    #@ if certificate and privateKey:
    secret: #@ "{}-tls".format(data.values.ingressDomain)
    #@ end
    #@ if data.values.ingressClass:
    class: #@ data.values.ingressClass
    #@ end
  #@ if data.values.storageClass or data.values.storageUser or data.values.storageGroup:
  storage:
    #@ if data.values.storageClass:
    class: #@ data.values.storageClass
    #@ end
    #@ if data.values.storageUser:
    user: #@ int(data.values.storageUser)
    #@ end
    #@ if data.values.storageGroup:
    group: #@ int(data.values.storageGroup)
    #@ end
  #@ end
  #@ pull_secrets = image_pull_secrets()
  #@ if pull_secrets:
  environment:
    secrets:
      pull: #@ pull_secrets
  #@ end
