#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("/helpers.star", "docker_config_json")

#@ host = data.values.imageRegistry.host
#@ username = data.values.imageRegistry.username
#@ password = data.values.imageRegistry.password or ""

#@ if host and username:
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-pull".format(host)
  namespace: #@ data.values.namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ base64.encode(docker_config_json(host, username, password))
#@ end
